### ISSUE TITLE
Good Job !

### ISSUE THREAD

**Issue by Qidian213** [ZQPei/deep_sort_pytorch#1]
来学习了 ，沙发！ 我也一直想做些扩展优化，无奈 tensorflow 不熟悉，再忙点就一直没有推进，多谢你的分享！

**Comment by ZQPei** [comment]
哈哈，我们可以互相交流学习
如果你觉得有帮助的话，可以给个star，谢谢你哈！

**Comment by Qidian213** [comment]
还没有跑通，不着急

**Comment by ZQPei** [comment]
你可以加我QQ交流：469823397

**Comment by Qidian213** [comment]
华科自动化考研群里有你，17智能。。。
