### ISSUE TITLE
Gpu instead of Cpu.

### ISSUE THREAD

**Issue by riyam68** [ZQPei/deep_sort_pytorch#102]
Hi,
Can anyone guide me about how can I use GPU instead of CPU?

**Comment by ZQPei** [comment]
It will choose GPU automaticly.

**Comment by riyam68** [comment]
why is cuda.available is returning false on my system. I have installed cuda 10.2 toolkit before I have cloned the project.

**Comment by ZQPei** [comment]
Your cuda version and pytorch version should match.
For instance, `pytorch_1.3.0_cu92` is not suitable for `cuda_10.2`.
Check (https://pytorch.org/get-started/previous-versions/)[https://pytorch.org/get-started/previous-versions/] for more information.
