### ISSUE TITLE
数据集格式问题

### ISSUE THREAD

**Issue by ggyybb** [ZQPei/deep_sort_pytorch#105]
1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？

**Comment by ggyybb** [comment]
> 1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
> 2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？

我知道怎么改图片了，但是训练一个epoch快结束的时候会出现这个问题：
![image](https://user-images.githubusercontent.com/61568153/76273617-44be1080-62b9-11ea-9be4-d3c21fcad116.png)
不知道为啥

**Comment by ggyybb** [comment]
> > 1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
> > 2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？
> 
> 我知道怎么改图片了，但是训练一个epoch快结束的时候会出现这个问题：
> Traceback (most recent call last):
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 197, in 
> main()
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 189, in main
> train_loss, train_err = train(epoch)
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 92, in train
> outputs = net(inputs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\项目\源码\检测\deep_sort\deep_sort\deep\model.py", line 94, in forward
> x = self.classifier(x)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\batchnorm.py", line 83, in forward
> exponential_average_factor, self.eps)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\functional.py", line 1693, in batch_norm
> raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256])
> 
> 不知道为啥？

我知道为啥了，对不起，打扰了，哈哈

**Comment by ggyybb** [comment]
还有一个问题：训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？ @ZQPei

**Comment by ggyybb** [comment]
刚刚那个问题我也知道了，不能放不同的ID，现在还有一个问题：
我用训练的是12个类别，运行检测跟踪程序的时候，出现了这个问题，应该是你用751类训练，但是我拿不出751类数据，我需要修改那里才可以匹配我训练的权重文件。
RuntimeError: Error(s) in loading state_dict for Net:
	size mismatch for classifier.4.weight: copying a param with shape torch.Size([12, 256]) from checkpoint, the shape in current model is torch.Size([751, 256]).
	size mismatch for classifier.4.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([751]).

**Comment by ggyybb** [comment]
我找到为啥类别不对了，打扰了，哈哈，我把问题关了

**Comment by pvtien96** [comment]
@ggyybb Hi, I'm currently getting the same issue, can you help me?
I successfully train the Market1501 dataset and it generates the checkpoints/ckpt17.pth file.
But when I try to inference the demo code with this new ckpt17.pth, I get the errors:
```
2020-04-18 17:38:40 [INFO]: Loading weights from ./detector/YOLOv3/weight/yolov3.weights... Done!
Traceback (most recent call last):
  File "yolov3_deepsort.py", line 155, in <module>
    with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
  File "yolov3_deepsort.py", line 38, in __init__
    self.deepsort = build_tracker(cfg, use_cuda=use_cuda)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/__init__.py", line 11, in build_tracker
    max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET, use_cuda=use_cuda)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep_sort.py", line 19, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
    self.net.load_state_dict(state_dict)
  File "/home/minhkv/anaconda3/envs/zqpei/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Net:
        size mismatch for classifier.4.weight: copying a param with shape torch.Size([1502, 256]) from checkpoint, the sha current model is torch.Size([751, 256]).
        size mismatch for classifier.4.bias: copying a param with shape torch.Size([1502]) from checkpoint, the shape in ct model is torch.Size([751]).
```
So how did you fix the error size mismatch?
Any suggestion? 
Many thanks!

**Comment by ggyybb** [comment]
> @ggyybb Hi, I'm currently getting the same issue, can you help me?
> I successfully train the Market1501 dataset and it generates the checkpoints/ckpt17.pth file.
> But when I try to inference the demo code with this new ckpt17.pth, I get the errors:
> 
> ```
> 2020-04-18 17:38:40 [INFO]: Loading weights from ./detector/YOLOv3/weight/yolov3.weights... Done!
> Traceback (most recent call last):
>   File "yolov3_deepsort.py", line 155, in <module>
>     with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
>   File "yolov3_deepsort.py", line 38, in __init__
>     self.deepsort = build_tracker(cfg, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/__init__.py", line 11, in build_tracker
>     max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep_sort.py", line 19, in __init__
>     self.extractor = Extractor(model_path, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
>     self.net.load_state_dict(state_dict)
>   File "/home/minhkv/anaconda3/envs/zqpei/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Net:
>         size mismatch for classifier.4.weight: copying a param with shape torch.Size([1502, 256]) from checkpoint, the sha current model is torch.Size([751, 256]).
>         size mismatch for classifier.4.bias: copying a param with shape torch.Size([1502]) from checkpoint, the shape in ct model is torch.Size([751]).
> ```
> 
> So how did you fix the error size mismatch?
> Any suggestion?
> Many thanks!

把Net（）里的类别数改为1501就行了

**Comment by pvtien96** [comment]
@ggyybb So where do I need to change the number of categories in the Net()? During training time or during inference time?
Please help me. Thanks!

**Comment by pvtien96** [comment]
@ggyybb Thanks, I think I figured it out! 
For someone who may need this, in the file feature_extractor.py, line 49, I changed to 
`def __init__(self, num_classes=1502 ,reid=False):`
I don't understand why @ZQPei wrote 
`def __init__(self, num_classes=751 ,reid=False):`
But currently after changing to 1502 the demo works with my custom trained model.
Any suggestions?

**Comment by china56321** [comment]
> @ggyybb Hi, I'm currently getting the same issue, can you help me?
> I successfully train the Market1501 dataset and it generates the checkpoints/ckpt17.pth file.
> But when I try to inference the demo code with this new ckpt17.pth, I get the errors:
> 
> ```
> 2020-04-18 17:38:40 [INFO]: Loading weights from ./detector/YOLOv3/weight/yolov3.weights... Done!
> Traceback (most recent call last):
>   File "yolov3_deepsort.py", line 155, in <module>
>     with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
>   File "yolov3_deepsort.py", line 38, in __init__
>     self.deepsort = build_tracker(cfg, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/__init__.py", line 11, in build_tracker
>     max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep_sort.py", line 19, in __init__
>     self.extractor = Extractor(model_path, use_cuda=use_cuda)
>   File "/home/minhkv/tienpv_DO_NOT_REMOVE/deep_sort_pytorch/deep_sort/deep/feature_extractor.py", line 14, in __init__
>     self.net.load_state_dict(state_dict)
>   File "/home/minhkv/anaconda3/envs/zqpei/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Net:
>         size mismatch for classifier.4.weight: copying a param with shape torch.Size([1502, 256]) from checkpoint, the sha current model is torch.Size([751, 256]).
>         size mismatch for classifier.4.bias: copying a param with shape torch.Size([1502]) from checkpoint, the shape in ct model is torch.Size([751]).
> ```
> 
> So how did you fix the error size mismatch?
> Any suggestion?
> Many thanks!

**Hi ,I have downloaded the Market-1501-v15.09.15 datasets,but i do not know how to train,Could you tell me how to train using deep_sort_pytorch ? Thanks**

**Comment by china56321** [comment]
> > 1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
> > 2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？
> 
> 我知道怎么改图片了，但是训练一个epoch快结束的时候会出现这个问题：
> Traceback (most recent call last):
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 197, in
> main()
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 189, in main
> train_loss, train_err = train(epoch)
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 92, in train
> outputs = net(inputs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\项目\源码\检测\deep_sort\deep_sort\deep\model.py", line 94, in forward
> x = self.classifier(x)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\batchnorm.py", line 83, in forward
> exponential_average_factor, self.eps)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\functional.py", line 1693, in batch_norm
> raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256])
> 
> 不知道为啥？

你好，我也遇到了这个问题？请问你是怎么解决的？

**Comment by pvtien96** [comment]
I hope I can help but unfortunatetly I don't understand chinese

**Comment by china56321** [comment]
> > 1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
> > 2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？
> 
> 我知道怎么改图片了，但是训练一个epoch快结束的时候会出现这个问题：
> Traceback (most recent call last):
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 197, in
> main()
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 189, in main
> train_loss, train_err = train(epoch)
> File "F:/项目/源码/检测/deep_sort/deep_sort/deep/train.py", line 92, in train
> outputs = net(inputs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\项目\源码\检测\deep_sort\deep_sort\deep\model.py", line 94, in forward
> x = self.classifier(x)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
> input = module(input)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\modules\batchnorm.py", line 83, in forward
> exponential_average_factor, self.eps)
> File "C:\Users\15251\Anaconda3\envs\SiamDW\lib\site-packages\torch\nn\functional.py", line 1693, in batch_norm
> raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256])
> 
> 不知道为啥？

Hi, i also encountered this ploblem,Could you tell me how did you solve it ?

**Comment by withtimesgo1115** [comment]
> 我找到为啥类别不对了，打扰了，哈哈，我把问题关了

解决了问题，啥也不说，真的是服了。跟越南老哥学学吧。

**Comment by ggyybb** [comment]
> > 我找到为啥类别不对了，打扰了，哈哈，我把问题关了
> 
> 解决了问题，啥也不说，真的是服了。跟越南老哥学学吧。

https://blog.csdn.net/weixin_40194996/article/details/104779138

**Comment by withtimesgo1115** [comment]
> > > 我找到为啥类别不对了，打扰了，哈哈，我把问题关了
> > 
> > 
> > 解决了问题，啥也不说，真的是服了。跟越南老哥学学吧。
> 
> https://blog.csdn.net/weixin_40194996/article/details/104779138

感谢分享，我又趟了一遍你走过的坑，但是他这个实现有问题，deep模块感觉没有用到，随便换个不同精度的权重上去效果一模一样，不知道你有没有发现。

**Comment by JAYCHOU2020** [comment]
> 1.数据集的图片image_size可以和market1501不一样么，还是得改一下？
> 2.训练集和测试集可以用不同的ID么，就是训练集放001，002，003号，测试集放004，005，006号？

请问你的训练数据的标签文件是什么格式的啊和MOT一样吗？

**Comment by ggyybb** [comment]
> > > > 我找到为啥类别不对了，打扰了，哈哈，我把问题关了
> > > 
> > > 
> > > 解决了问题，啥也不说，真的是服了。跟越南老哥学学吧。
> > 
> > 
> > https://blog.csdn.net/weixin_40194996/article/details/104779138
> 
> 感谢分享，我又趟了一遍你走过的坑，但是他这个实现有问题，deep模块感觉没有用到，随便换个不同精度的权重上去效果一模一样，不知道你有没有发现。

实现没有问题，本来deep的作用就不大，换了模型甚至会变差。
