### ISSUE TITLE
yolov3 vs reid model

### ISSUE THREAD

**Issue by antoniolq** [ZQPei/deep_sort_pytorch#107]
hello，I am a freshman here. I hava a question about the differences between yolov3 and reid? Can I use yolov3 to extract the features instead of reid model?

**Comment by khayliang** [comment]
yolov3 is the model for detecting the bounding boxes of the persons in the camera frame. 

However, it is not capable of comparing the features between the appearance of the tracked person and other people within the camera frame. To do that, we need to use the reid model to see if they match.

**Comment by antoniolq** [comment]
Thank you very much!
