### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by samyhocine** [ZQPei/deep_sort_pytorch#115]
Hi,

I really think that you are pushing the DeepSort original algorithm into something really great :)
However you will almost be alone in this adventure, why ?

The GPLv3 is the worst licence ever, why ? No one in the industry will help you or want to improve this project.

GPLv3 is a parasite. GPLv2 would have been a better choice protecting your work, protecting the Freedom of DeepSort.
Using DeepSort_pytorch under GPLv3 on a system forces to put every piece of code under GPLv3 of this system even if DeepSort_pytorch is a tiny module inside a very big and complex solution.
GPLv2 lets everyone build a solution without forcing them to share the code of the entire system, only modules under GPLv2.

A lot of modules used in the industry are under the GPLv2 and they have a GitHub maintained by the industry and a lot of people around the world.

Now it's a useless piece of work that will not be used anywhere near the industry (aka the real world). It will just be good for a reasearch paper and will be forgoten just after that.

JDE (https://github.com/Zhongdao/Towards-Realtime-MOT) are doing a less interesting job compared to DeepSort_pytorch but because the algorithm is Under the MIT licence, it is more likely to be helped/pushed by the industry.

You want to be friend with the industry and the academic world, push your work under the MIT, the BSD or the CC licence and even the GPLv2.
You want your work to be used nowhere, push your work under the GPLv3. 

Think about it for your next work ;)

Best regards,

Samy H.

**Comment by ZQPei** [comment]
@samyhocine 
Thank you for telling me the importance of License.
I never thought it would be so important.
It is a very good advice of changing it from GPL to MIT.
Thanks again!
Ziqiang P.
