### ISSUE TITLE
Tracker will not update when no object is detected?

### ISSUE THREAD

**Issue by dli2016** [ZQPei/deep_sort_pytorch#117]
https://github.com/ZQPei/deep_sort_pytorch/blob/3bf01aece03e2068d4231673358a945748a2b6e0/yolov3_deepsort.py#L85
Based on the lines 76 and 85 in the file yolov3_deepsort.py, it seems that the tracker will not update when there is no object detected, which maybe not correct?

**Comment by ZQPei** [comment]
Yes, the `deep sort` tracker relies heavily on the results of detector since it is a detection based tracker.

**Comment by dli2016** [comment]
> Yes, the `deep sort` tracker relies heavily on the results of detector since it is a detection based tracker.

不好意思我用中文吧，英语不好~~
是的，检测的效果会大大影响跟踪的性能。从两方面来解释吧：1.就跟踪而言，即便有一些帧没有检测到目标，其实还会继续做预测的，比如deepsort中的卡尔曼滤波，所以即便没有目标检测到，应该依旧执行predict；2.从代码上来分析，即便有目标检测到了，但很可能检测到的没有行人这一类，因为您的代码里在if语句中还会继续筛选出标签为人(0)的目标框，这时候即便没有行人检测到依然会执行跟踪的，这时候逻辑上就矛盾了。综上，即便没有目标检测到，或者没有行人检测到，还是要跟踪的。
如果我的理解有问题的话，请您指出，谢谢！

**Comment by ZQPei** [comment]
依你这么说，那行人离开视频了怎么办？
在`deep_sort/sort/tracker.py`中，有一个参数`max_age`，意思是如果在一定帧数内没有再次检测到这个行人，就删除他对应的tracker。每一帧都要用检测得到的bbox来进行tracker的更新，在tracker里面会有卡尔曼滤波来预测位置。

**Comment by dli2016** [comment]
> 依你这么说，那行人离开视频了怎么办？
> 在`deep_sort/sort/tracker.py`中，有一个参数`max_age`，意思是如果在一定帧数内没有再次检测到这个行人，就删除他对应的tracker。每一帧都要用检测得到的bbox来进行tracker的更新，在tracker里面会有卡尔曼滤波来预测位置。

恩，是的，有一个max_age，离开视频，也就意味着time_since_update那个变量（如果没记错的话）或持续加一，累积到max_age就会把track的状态改为is_delete。其实抛开tracking不说，但就代码上，因为if bboxes is not None条件内部，也有可能没有检测到行人这一类目标，您依然执行了Deepsort update的函数，那bboxes is None为什么就不执行？觉得他们是一样的。从跟踪的角度来讲，新检测到目标只是在做预测模型的修正吧，您可以发现其实卡尔曼滤波那个类里其实是有两个变量描述运动状态的，即便没有目标检测到，track应该也要做预测，预测他的位置，只是不再update了，我觉得如果在获取output时，如果我们去掉track.time_since_update > 1这个条件，即便没有目标检测到，还是可以拿到轨迹当前帧预测出的位置的。
以上仅是自己的理解，非常感谢您的回答，谢谢！

**Comment by ZQPei** [comment]
你说的是对的，在`bbox`为`None`的时候，也应该进行update。
谢谢你的提醒，我会尽快改正。

**Comment by dli2016** [comment]
恩恩，谢谢，您的project为大家提供很大的便利！
