### ISSUE TITLE
关于数据集的一些问题

### ISSUE THREAD

**Issue by renping0535** [ZQPei/deep_sort_pytorch#119]
Hi, ZQ

Great to see your repo!
最近在处理一些tracking by detection的事情，属于driving的场景：
1. detection部分，计划用yolo3，数据集打算用BDD100K，因为看这个数据集应该是目前最新的了吧，共有10类关于“交通参与者”的信息；
2. tracking部分，想和sort或者deep sort整合，但是只想tracking某几类object，比如机动车道上的car（轿车），bus（公交车），truck（卡车）；
不知道这样可不可行？要detect共10个类别，但是只track其中3个类别，就像前面说的那样~

感谢！

**Comment by ZQPei** [comment]
可行，但是建议用sort进行跟踪，因为deep sort需要进行Reid。
