### ISSUE TITLE
Get pool result after doing tracking?

### ISSUE THREAD

**Issue by changwh** [ZQPei/deep_sort_pytorch#135]
Hello, I get good result through runing the origin code. To get a better result, I change the detector. According to my test, the detector I changed is accurate. But when I combine the detector and tracker, I find the bbox is moved to the upper left of where it should be.
I wonder why it happened? And how to get the accurate tracking result? Can anyone help?

**Comment by changwh** [comment]
OK, I have found out the problem.
The input of tracker should be `xc_yc_w_h`, rather than `xywh`.

**Comment by edgexspear** [comment]
> Hello, I get good result through runing the origin code. To get a better result, I change the detector. According to my test, the detector I changed is accurate. But when I combine the detector and tracker, I find the bbox is moved to the upper left of where it should be.
> I wonder why it happened? And how to get the accurate tracking result? Can anyone help?

could u share your detector code please?

**Comment by changwh** [comment]
> 
> 
> > Hello, I get good result through runing the origin code. To get a better result, I change the detector. According to my test, the detector I changed is accurate. But when I combine the detector and tracker, I find the bbox is moved to the upper left of where it should be.
> > I wonder why it happened? And how to get the accurate tracking result? Can anyone help?
> 
> could u share your detector code please?

Just Cascade RCNN in MMDetection.

**Comment by edgexspear** [comment]
> > > Hello, I get good result through runing the origin code. To get a better result, I change the detector. According to my test, the detector I changed is accurate. But when I combine the detector and tracker, I find the bbox is moved to the upper left of where it should be.
> > > I wonder why it happened? And how to get the accurate tracking result? Can anyone help?
> > 
> > 
> > could u share your detector code please?
> 
> Just Cascade RCNN in MMDetection.

how to replace Yolo by Mmdetection in this code?

**Comment by changwh** [comment]
> 
> 
> > > > Hello, I get good result through runing the origin code. To get a better result, I change the detector. According to my test, the detector I changed is accurate. But when I combine the detector and tracker, I find the bbox is moved to the upper left of where it should be.
> > > > I wonder why it happened? And how to get the accurate tracking result? Can anyone help?
> > > 
> > > 
> > > could u share your detector code please?
> > 
> > 
> > Just Cascade RCNN in MMDetection.
> 
> how to replace Yolo by Mmdetection in this code?

Use apis of mmdet  `inference_detector`, `init_detector` to get detection result with config file and weight file. Then change them into the input of the tracker in deepsort.

**Comment by edgexspear** [comment]
i will try thankyou , do u have a bette result with MMDET?

**Comment by changwh** [comment]
> 
> 
> i will try thankyou , do u have a bette result with MMDET?

Yes, about 7%.
