### ISSUE TITLE
SIZE of output 

### ISSUE THREAD

**Issue by edgexspear** [ZQPei/deep_sort_pytorch#141]
dear @ZQPei 
input : 1 min video
output :300+MB 
size of output is too large , how can i get a smaller output video ?

**Comment by ShamEgo** [comment]
Writing the output video to a .mp4 reduces the size. Alternatively sending it through ffmpeg converter(converting to .mp4) will reduce the size drastically.

# to write to mp4 change yolov3_deepsort.py
# create video writer
`fourcc = cv2.VideoWriter_fourcc(*'MP4V')`

and change name of the output video to .mp4

# path of saved video and results
`self.save_video_path` = os.path.join(self.args.save_path, "results.mp4")`
