### ISSUE TITLE
Why u have used new model

### ISSUE THREAD

**Issue by lakshmi1444** [ZQPei/deep_sort_pytorch#148]
why u have used another model for features cant we use yolo model features?

**Comment by ZQPei** [comment]
yes， it is possible.
however, if we use yolo features for reid in deep sort, we shall train the whole network with a new dataset that contains both detection bounding box and person id.

**Comment by lakshmi1444** [comment]
Suppose if i have trained yolov3 model for particular object like aeroplane.
Can we use  feature extractor as the last layer output of yolo
