### ISSUE TITLE
测试视频时跟踪框不能十分准确框出人

### ISSUE THREAD

**Issue by 853498747** [ZQPei/deep_sort_pytorch#15]
大神你好，我在测试时发现跟踪框总是和真实检测框有一点偏移，偏向前进方向一点.请问这是什么原因？我要将yolo改为maskrcnn，但是跟踪框和检测框不重合导致我无法进行下一步．

**Comment by ZQPei** [comment]
因为跟踪框是预测的bbox，和检测框不一样。你在跟踪框和检测框匹配之后，把显示的框改成检测框就可以了。
