### ISSUE TITLE
Load yolov4.weights and yolov4.cfg all out_boxes are nan

### ISSUE THREAD

**Issue by Damon0626** [ZQPei/deep_sort_pytorch#157]
The yolov3_deepsort.py gives me a good result. When updating yolov3 to yolov4, I‘m in a jam. There's no boxes when the detector go forwarding. I downloaded the weights and cfg file from https://github.com/AlexeyAB/darknet.
See the following detail pics.
[1]yaml file 
![image](https://user-images.githubusercontent.com/33386246/86456814-3a86bd00-bd55-11ea-932e-9bdbe6e9aef5.png)
[2]detector.py
![image](https://user-images.githubusercontent.com/33386246/86457024-994c3680-bd55-11ea-98cc-12b1dd1aa715.png)
[3]out_boxes result
the out_boxes['x'] is nan, out_boxes['a'] and out_boxes['n'] have values.
![image](https://user-images.githubusercontent.com/33386246/86457219-e29c8600-bd55-11ea-95e4-d4c2b881003a.png)

I have read the darknet.py. The cfgfile and weightfile loaded well. I have no idea how to debug. Can u help me.

**Comment by WangHR1997** [comment]
Actually,If you are careful enough,you will find that the output of function **print_network()**  in darknet.py doesn't include the 113rd layer,which is a 'route' block.If we find this block in .cfg file,we get layers=-1,-2,-5,-6,which includes four branches.But the process of 'route' blocks in the original code (see **create_network** in darknet.py) supports most 2 branches,we need to modify these codes(a very easy job,just update prev_filters with the sum(output_filters[l] for l in layers) ).Also remember to modify the codes corresponding to 'route' in function forward()(also an easy job,just do concatentions one by one).Finally,yolov4 uses a new kind of activation Mish(x)=x*softplus(x)*tanh().You need to define the class by yourself(It seems that torch doesn't include this activation?),and then find add your Mish to somewhere adequate.
That are what I have done so far.After doing this,Yolov4 works fine in my machine and produce better results than yolov3.

**Comment by Damon0626** [comment]
copy that, thanks very much.

**Comment by prabinaneupane** [comment]
@Damon0626 @codingandstudy have you guys been able to implement yolov4 on deepsort. If yes, could you please help me out. For example how to you initialize the detector_build(). I saw that your darknet.py file does not contain any class similar to Yolov3 used in darknet.py of yolov3?
