### ISSUE TITLE
matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by xiangxu007** [ZQPei/deep_sort_pytorch#162]
File "yolov3_deepsort.py", line 156, in <module>
    vdo_trk.run()
  File "yolov3_deepsort.py", line 102, in run
    outputs = self.deepsort.update(bbox_xywh, cls_conf, im)
  File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/deep_sort.py", line 44, in update
    self.tracker.update(detections)
  File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 69, in update
    self._match(detections)
  File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 115, in _match
    self.tracks, detections, confirmed_tracks)
  File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linear_assignment.py", line 140, in matching_cascade
    track_indices_l, unmatched_detections)
  File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linear_assignment.py", line 60, in min_cost_matching
    row_indices, col_indices = linear_assignment(cost_matrix)
  File "/home/jwd/anaconda3/envs/deep_sort/lib/python3.6/site-packages/scipy/optimize/_hungarian.py", line 93, in linear_sum_assignment
    raise ValueError("matrix contains invalid numeric entries")
ValueError: matrix contains invalid numeric entries.

How can i solved? Could you help me? Thank you.

**Comment by xiangxu007** [comment]
> File "yolov3_deepsort.py", line 156, in
> vdo_trk.run()
> File "yolov3_deepsort.py", line 102, in run
> outputs = self.deepsort.update(bbox_xywh, cls_conf, im)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/deep_sort.py", line 44, in update
> self.tracker.update(detections)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 69, in update
> self._match(detections)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 115, in _match
> self.tracks, detections, confirmed_tracks)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linear_assignment.py", line 140, in matching_cascade
> track_indices_l, unmatched_detections)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linear_assignment.py", line 60, in min_cost_matching
> row_indices, col_indices = linear_assignment(cost_matrix)
> File "/home/jwd/anaconda3/envs/deep_sort/lib/python3.6/site-packages/scipy/optimize/_hungarian.py", line 93, in linear_sum_assignment
> raise ValueError("matrix contains invalid numeric entries")
> ValueError: matrix contains invalid numeric entries.
> 
> How can i solved? Could you help me? Thank you.



> File "yolov3_deepsort.py", line 156, in
> vdo_trk.run()
> File "yolov3_deepsort.py", line 102, in run
> outputs = self.deepsort.update(bbox_xywh, cls_conf, im)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/deep_sort.py", line 44, in update
> self.tracker.update(detections)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 69, in update
> self._match(detections)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/tracker.py", line 115, in _match
> self.tracks, detections, confirmed_tracks)
> File "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linear_assignment.py", line 140, in matching_cascade
> track_indices_l, unmatched_detections)
> File 

> "/home/jwd/MOT/deep_sort_pytorch-master/deep_sort/sort/linea

**Comment by tomatopuree** [comment]
Hello @xiangxu007 how did you end up getting around this error?
