### ISSUE TITLE
realtime testing

### ISSUE THREAD

**Issue by sandeshshrestha45** [ZQPei/deep_sort_pytorch#17]
Hello ZQPei,

How can i modify the code in demo.py to use the live stream directly from the webcamera in real time?

**Comment by ZQPei** [comment]
Hello, @sandeshshrestha45 
Opencv VideoCapture support read video stream from video file, local cam, web cam.
For a local camera, `cv2.VideoCapture(0)`.
For a web camera, `cv2.VideoCapture(cam_url)`.

**Comment by sandeshshrestha45** [comment]
Dear ZQPei,

In your code, you have used argparse for reading video.What changes do i have to make to avoid it and directly read the video from  webcam?
