### ISSUE TITLE
merge two checkpoints

### ISSUE THREAD

**Issue by sandeshshrestha45** [ZQPei/deep_sort_pytorch#18]
Dear ZQPei,

Is it possible to implement tracking two different classes in the same video? I have separately trained the re-identification model for humans and vehicles so I got two separate checkpoints. How can I track both humans and vehicles in the same video?

**Comment by ZQPei** [comment]
Yes, it is possible.
You can get that by creating two Deep_sort trackers to track seperately for human and vehicle class.
