### ISSUE TITLE
请问我想训练车辆跟踪的模型、我应该怎么做呢？

### ISSUE THREAD

**Issue by louxy126** [ZQPei/deep_sort_pytorch#2]
你好、谢谢你提供的分享！我最近在学习车辆跟踪方面的内容、请问如果我想要用你的代码进行实现、需要训练和替换哪些东西呢？谢谢啦

**Comment by ZQPei** [comment]
两个部分，先检测车辆，再跟踪车辆。
检测车辆，你需要标注有车辆的目标检测数据集，并且训练检测模型
跟踪车辆，你可以考虑只用sort，如果要用deepsort，那么你还需要提取车辆的特征，你需要一个针对车辆的分类数据集，并且重新训练deepsort中的特征提取模型。
所以最关键的还是数据集加训练模型。

**Comment by louxy126** [comment]
star给你啦！
还想请教个问题，你这边用的是coco上训练的weights，那是不是我用自己的数据在pytorch上训连一个行人+自行车的weights将原本的weights替换掉就可以实现行人+自行车的跟踪了？假设deep_sort已经完成了特征提取。
coco数据集里本来就有行人和自行车，可不可以对你的代码做一些小的改动，weights还是用你这里给的，然后实现对行人和自行车的跟踪？还是假设假设deep_sort已经完成了特征提取。
我才开始学习这方面的东西，问题可能比较蠢，多多见谅，谢谢啦。

**Comment by ZQPei** [comment]
你的意思是说，只用yolov3.weights中的行人和自行车的参数，这样是可以的，你可以把这些参数另外保存到一个文件中。
另外，如果你的场景包含一些特殊场景，建议你自己搜集一些数据集，然后在现有参数的基础上进行微调。

**Comment by ZQPei** [comment]
这个我建议你可以看一下其他的算法，sort本身是用速度预测位置的，在连续帧下效果才好吧

**Comment by dongfangduoshou123** [comment]
意思是DeepSort不能跟踪general目标？特定类型的目标需要重新训练才能跟？

**Comment by ZQPei** [comment]
> 意思是DeepSort不能跟踪general目标？特定类型的目标需要重新训练才能跟？

没错，不同的目标需要重新训练不同的REID模型，因为MOT比赛基本上是针对行人的，而且行人目标多，容易出现遮挡，所以对行人进行REID是很有必要的。
如果目标很少，而且不会出现重叠遮挡等，其实SORT效果已经很好了。
所以针对多目标，你可以分不同的目标，针对性的训练REID。

**Comment by dongfangduoshou123** [comment]
> > 意思是DeepSort不能跟踪general目标？特定类型的目标需要重新训练才能跟？
> 
> 没错，不同的目标需要重新训练不同的REID模型，因为MOT比赛基本上是针对行人的，而且行人目标多，容易出现遮挡，所以对行人进行REID是很有必要的。
> 如果目标很少，而且不会出现重叠遮挡等，其实SORT效果已经很好了。
> 所以针对多目标，你可以分不同的目标，针对性的训练REID。

我不做REID，我是用于车的跟踪计数，跟踪器能达到能跟上目标不丢（防止重复计数），目标真正消失时，停止跟踪就可以了，很多跟踪算法对恶劣天气如雾天时会有跟踪漂移跟丢的现象，sort跟踪你有没有测过恶劣天气的跟踪效果？ 好的花我想转为caffe2 cpp 用于部署。
刚才测了一下你这个实现的只跟踪的话速度还可以能达到120帧一秒;
耗时都在yolov3目标检测上了，你这个yolov3目标检测速度方面优化空间很大！

**Comment by ZQPei** [comment]
> 耗时都在yolov3目标检测上了，你这个yolov3目标检测速度方面优化空间很大！

这个只是一个demo，真正要部署的话，还是用cpp吧，你可以用caffe2，libtorch，也可以用YOLOv3作者的C代码。

> 有没有测过恶劣天气的跟踪效果？

因为目前的跟踪算法还是依赖于检测的精度，你说的雾天跟丢的现象，主要还是来源于*雾天的检测效果不好*。你可以针对雾天做一下去雾，再进行检测和跟踪。
关于去雾，可以参考我的这个repo：https://github.com/ZQPei/Haze_Removal_cpp
还有python版本：https://github.com/ZQPei/Haze_Removal_python

**Comment by dongfangduoshou123** [comment]
雾天我们能检测到，专门针对恶劣天气样本训了，我们导致跟丢的原因是跟踪不鲁棒。

**Comment by ZQPei** [comment]
> 雾天我们能检测到，专门针对恶劣天气样本训了，我们导致跟丢的原因是跟踪不鲁棒。

那你要用deep sort的话，你得制作一个包含正常天气和雾天的车辆REID数据集，然后训练deep sort中的REID模型。因为deep sort里面的deep就是一个REID模型。

**Comment by dongfangduoshou123** [comment]
![hazeremove](https://user-images.githubusercontent.com/22514720/55128494-ba83a780-514e-11e9-9b5a-57e57e6525a0.jpg)这种效果不敢用，说明对于不同的场景去雾参数不固定。。。。
那个到好说，改一下deep sort Reid跟踪逻辑符合需求就可以了。（因为deep sort里面的deep就是一个REID模型。）关键是跟的好不好。

**Comment by dongfangduoshou123** [comment]
你是PZQ，我是WZQ。。。。。

**Comment by ZQPei** [comment]
你是高速公路场景，这种场景下一般很少出现遮挡重叠的现象，其实我觉得用sort效果应该就挺好的。
如果还是会出现跟丢的情况，你可以把sort里面的间隔调大一点。

**Comment by ZQPei** [comment]
> 你是PZQ，我是WZQ。。。。。

哈哈哈😂

**Comment by chengzilizhi** [comment]
你好，我也想做车辆的检测与跟踪，请问车辆的特征提取该怎么做？

**Comment by ZQPei** [comment]
> 你好，我也想做车辆的检测与跟踪，请问车辆的特征提取该怎么做？

你好，首先你需要车辆的重识别数据集，然后进行训练。

**Comment by chengzilizhi** [comment]
> > 你好，我也想做车辆的检测与跟踪，请问车辆的特征提取该怎么做？
> 
> 你好，首先你需要车辆的重识别数据集，然后进行训练。

请问你的代码里有训练的这一部分吗？能否详细描述一下，非常感谢！

**Comment by ZQPei** [comment]
> 请问你的代码里有训练的这一部分吗？能否详细描述一下，非常感谢！

有的，请参考`train.py`。

**Comment by jiyu98** [comment]
> 雾天我们能检测到，专门针对恶劣天气样本训了，我们导致跟丢的原因是跟踪不鲁棒。

你们雾天的先去做去除雾吗？车辆检测你们用的yolov3吗

**Comment by zengdiqing1994** [comment]
> > 你好，我也想做车辆的检测与跟踪，请问车辆的特征提取该怎么做？
> 
> 你好，首先你需要车辆的重识别数据集，然后进行训练。

请问这个数据集要怎么制作呢？是和market1501一样的格式吗？

**Comment by Revendell** [comment]
请问关于车辆重识别的数据集要怎么制作呢？

**Comment by ZQPei** [comment]
> > > 你好，我也想做车辆的检测与跟踪，请问车辆的特征提取该怎么做？
> > 
> > 
> > 你好，首先你需要车辆的重识别数据集，然后进行训练。
> 
> 请问这个数据集要怎么制作呢？是和market1501一样的格式吗？

你好@ zengdiqing1994
是的，先进行车辆的重识别网络训练

**Comment by ZQPei** [comment]
> 请问关于车辆重识别的数据集要怎么制作呢？

可以把同一辆车的不同图片放在一个文件夹内，不同车辆分别用ID作为文件夹名

**Comment by 201814476285951** [comment]
> 你好、谢谢你提供的分享！我最近在学习车辆跟踪方面的内容、请问如果我想要用你的代码进行实现、需要训练和替换哪些东西呢？谢谢啦

@louxy126 你好，请问你做好数据集之后具体训练程序是怎么改的？我的还是这样报错。。。宝峰哭泣，谢谢解答，希望能抽时间回复一下。

**Comment by Revendell** [comment]
用deep sort没有实现车辆检测加跟踪，我是使用sort+yolov3实现了目标检测加跟踪，代码如下：https://github.com/cfotache/pytorch_objectdetecttrack    
只要修改object_tracker.py代码里的配置就行，将yolov3训练得到的目标检测模型放入config里面然后运行python3 object_tracker.py

目标检测yolov3代码可以参考https://github.com/spmallick/learnopencv/tree/master/YOLOv3-Training-Snowman-Detector


------------------ 原始邮件 ------------------
发件人: "201814476285951"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 晚上8:31
收件人: "ZQPei/deep_sort_pytorch"<deep_sort_pytorch@noreply.github.com>;
抄送: "胡涛"<2312237896@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZQPei/deep_sort_pytorch] 请问我想训练车辆跟踪的模型、我应该怎么做呢？ (#2)



 
你好、谢谢你提供的分享！我最近在学习车辆跟踪方面的内容、请问如果我想要用你的代码进行实现、需要训练和替换哪些东西呢？谢谢啦
  
@louxy126 你好，请问你做好数据集之后具体训练程序是怎么改的？我的还是这样报错。。。宝峰哭泣，谢谢解答，希望能抽时间回复一下。

**Comment by yustaub** [comment]
@Revendell 老哥，请问一下如果想要替换yolov3需要在哪些地方改动呢

**Comment by Revendell** [comment]
暂时还没yolov3+sort的版本，所以换不了，如果换，得自己重新写代码





------------------ 原始邮件 ------------------
发件人: yustaub <notifications@github.com&gt;
发送时间: 2020年2月14日 23:06
收件人: ZQPei/deep_sort_pytorch <deep_sort_pytorch@noreply.github.com&gt;
抄送: Hutao <2312237896@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ZQPei/deep_sort_pytorch] 请问我想训练车辆跟踪的模型、我应该怎么做呢？ (#2)




@Revendell 老哥，请问一下如果想要替换yolov3需要在哪些地方改动呢

**Comment by ggyybb** [comment]
我替换了我自己训练的车辆检测，你们可以看一下，但是reid还没有重新训练，速度还可以https://github.com/ggyybb/yolov3-tiny-deepsort-pytorch-cardetection.git

**Comment by duyao-art** [comment]
@louxy126 ,同学你好，我最近也在做关于车辆的识别和跟踪，车辆本身划分了六种，但是我将我训练修改好的yolov3.cfg 和对应的weights, data.name文件替换加载进来之后，暂时deep的weight还是用的行人重识别训练出来的weight,  我在实际代码运行的过程中，可以跑，但是detection number 和 tracking number都一直是零，但是我单独在yolov3 project里面跑的时候就可以对加载的视频检测出挺好的结果。请问时候需要在deep_sort 工程中修改其他的东西呢？除了上述的那些替换之外
我还将mask = cls_ids 这个地方后面的==0去掉了，保证可以检测出多个类别。

**Comment by xiang1107** [comment]
@duyao-art 请问您解决了吗，我也是与你一样，一直都是0。

**Comment by duyao-art** [comment]
@xiang1107  没有，这个问题我都好久了哎

**Comment by xiang1107** [comment]
> @xiang1107 没有，这个问题我都好久了哎
我看了一下，自己训练保存的“pth"参数模型导入后，貌似没有导入成功，里面的参数值都是0，所以可能会造成这种原因

**Comment by xiang1107** [comment]
@duyao-art 我看了一下，自己训练保存的“pth"参数模型导入后，貌似没有导入成功，里面的参数值都是0，所以可能会造成这种原因

**Comment by duyao-art** [comment]
哈哈哈，英雄所见略同，我也是今天早上刚刚发现的这个问题，加一下微信吧，我们再讨论。DUYAO993379914

xiang1107 <notifications@github.com> 于2020年6月2日周二 上午9:47写道：

**Comment by NTULJ** [comment]
> > 请问你的代码里有训练的这一部分吗？能否详细描述一下，非常感谢！
> 
> 有的，请参考`train.py`。

大佬好，请问我要用这个模型训练以实现多种树木的识别，我该怎么操作呢？因为您的代码和yolov3官方代码布局不同，我也不是很了解，烦请解答😂
