### ISSUE TITLE
在追踪时候，出现很多跟踪框的问题

### ISSUE THREAD

**Issue by xiaoxiaotao** [ZQPei/deep_sort_pytorch#21]
您好，我在跑您的demo时，发现当一个人站着动的时候，他的周围会出现很多跟踪框，而且id都不一样，我想问下我是哪里做的不对吗，谢谢！

**Comment by ZQPei** [comment]
只有在检测器YOLO v3检测到目标后，才会进行跟踪，这说明在你的视频场景下，YOLOv3的虚检率很高，可能原因是你的视频场景和通用检测数据集COCO差距较大，你可以分享一下视频场景看看吗？

**Comment by xiaoxiaotao** [comment]
抱歉，是我这里参数没改好，deep_sort.py 里的第13行的self.nms_max_overlap=1.0;把这个改小一点就好了，感谢回复。
