### ISSUE TITLE
deep_sort on custom video 

### ISSUE THREAD

**Issue by adouwitti** [ZQPei/deep_sort_pytorch#22]
hello @ZQPei ,  i hope that you are doing well. i am going to use deep_sort to track custom objects (human head), i have darknet on my dataset ,  i have yolov3 model trained on head dataset.  when i tried to use deep-sort_yolov3 repository, the identification is erroneous. there is a huge difference between the ids of tracked objects. i want to use  the original deep_sort  repository, in order to track human in my own video. in deep_sort ,the detection ground truth is required. since i don't have the groundtruth label of my video, i am wondering , how can i use deep_sort to track objects in custom video. your suggestion will  be helpful.

**Comment by ZQPei** [comment]
hello @adouwitti 
Since your goal is tracking human head, then original deep_sort repository will not be useful. Because that is for tracking human.
Here is my suggestions,
1. use SORT algorithm. SORT is basicly part of deep sort without deep feature, and is easy to run. However, SORT is bad at occlusion problems.
2. still use deep sort algorithm. But you will nead to **train a good deep CNN model to compute human head feature** first. You cannot use the parameter in `ckpt.t7` in my repo directly, because it is for extracting human feature. Same reason on original deep sort repo.

**Comment by adouwitti** [comment]
@ZQPei  thanks for your response. i will not use SORT since it suffers from occlusion. first , i want to test your repository on my video.

**Comment by adouwitti** [comment]
@ZQPei  hello, i tried to run you demo on windows (cpu), but i couldnot , i was getting this message "  Torch not compiled with CUDA enabled " . i tried to run it on server (gpu) also, i am getting another error "cannot connect to x server". i  wanna test   original deep_sort  on my video to track people, since the code requires detection labels, i think that i should modify the code so that i can  test it on my video.  thanks

**Comment by ZQPei** [comment]
@adouwitti 
1. If you want run on windows(cpu), please comment any line with `net = net.cuda()` or `x = x.cuda()`, and it will be super slow running on cpu.
2. If you want run it on server(gpu) without x server, which is a common user interface of linux, you should comment `cv2.imshow(...)` and `cv2.waitKey(...)`. The result video will be saved automaticly by the control flag `self.write_video = True`.
3. You can also generate and save your detection results to feed into original deep_sort codes.

**Comment by adouwitti** [comment]
thanks for response.  i tried your suggestion and the error has disappeared. is there a script that generate detections for deep_sort ?  i am getting this 
![image](https://user-images.githubusercontent.com/44825125/56630457-08bf9400-6684-11e9-952c-19da31c9b375.png)
. thanks in advance

**Comment by ZQPei** [comment]
You overwrote my code, and error occurs...
`identity` shall be a digit number, and what is `i` in your code?

**Comment by adouwitti** [comment]
i didn't modify your code. but that message occurs

**Comment by ZQPei** [comment]
OK, this is a bug.
Can you tell me more information about it please?

**Comment by m-peker** [comment]
> hello @ZQPei , i hope that you are doing well. i am going to use deep_sort to track custom objects (human head), i have darknet on my dataset , i have yolov3 model trained on head dataset. when i tried to use deep-sort_yolov3 repository, the identification is erroneous. there is a huge difference between the ids of tracked objects. i want to use the original deep_sort repository, in order to track human in my own video. in deep_sort ,the detection ground truth is required. since i don't have the groundtruth label of my video, i am wondering , how can i use deep_sort to track objects in custom video. your suggestion will be helpful.

Hi,

Could you share the yolov3 model you train on the head dataset. We need a model like this.

Best Regards.

**Comment by adouwitti** [comment]
hi @m-peker , sorry I don't have permission  because, I was in internship when I trained yolov3 on head dataset. but if you have the dataset, I suggest you to have a look at this link https://github.com/AlexeyAB/darknet in order to train the model.

**Comment by m-peker** [comment]
@adouwitti Thank you for your response. I know the training processes. But it takes too long. There are many images. And they all need to be labeled. I understand you too. Thanks again.

**Comment by adouwitti** [comment]
you are welcome. I am sorry,
 I don't have the permission. thanks for your understanding.
