### ISSUE TITLE
Track IDs getting updated too quickly

### ISSUE THREAD

**Issue by harshsp31** [ZQPei/deep_sort_pytorch#23]
Hi @ZQPei. Thanks for the great implementation of Deep Sort. However I had a concern, the track IDs are getting updated way too quickly in some videos, like the track IDs change from 28 to 38 to 51 in a few seconds. Could you please tell me how can I avoid this?

**Comment by ZQPei** [comment]
Hi @harshsp31. 
You can set `n_init` in `sort/tracker.py` a bit larger, or set `max_cosine_distance` in `deep_sort.py` a bit smaller. Have a Try.

**Comment by harshsp31** [comment]
Hi @ZQPei ,
Thanks for the fast reply, I already tried doing that, but the results are not that satisfactory. Do you think if I increase the feature vector size in DeepSort, would it make a difference or a tweaked loss function would be better?

**Comment by ZQPei** [comment]
Increasing the feature vector will not do much better. You can increase the complexity of CNN model and try triplet loss function, etc.

**Comment by harshsp31** [comment]
Will do that, Thanks!
