### ISSUE TITLE
ModuleNotFoundError: No module named 'fastreid'

### ISSUE THREAD

**Issue by susuhu** [ZQPei/deep_sort_pytorch#233]
I didn't add any arguments for --fastreid, but it gives this error. 
why is this happening?

**Comment by MrRangerss** [comment]
Because fastreid is used in the files  __init__.py, deep_sort.py and feature_extractor.py, and these three files are in deep_sort folder. So, if you comment out all the codes about fastreid in these three files, the error will be solved.

**Comment by susuhu** [comment]
> Because fastreid is used in the files __init__.py, deep_sort.py and feature_extractor.py, and these three files are in deep_sort folder. So, if you comment out all the codes about fastreid in these three files, the error will be solved.

but shouldn't below code in deepsort.py skip fastreid when I don't set  arguments for --fastreid?
```python
  if args.fastreid:
      cfg.merge_from_file(args.config_fastreid)
      cfg.USE_FASTREID = True
  else:
      cfg.USE_FASTREID = False
```

**Comment by MrRangerss** [comment]
> > Because fastreid is used in the files **init**.py, deep_sort.py and feature_extractor.py, and these three files are in deep_sort folder. So, if you comment out all the codes about fastreid in these three files, the error will be solved.
> 
> but shouldn't below code in deepsort.py skip fastreid when I don't set arguments for --fastreid?
> 
> ```python
>   if args.fastreid:
>       cfg.merge_from_file(args.config_fastreid)
>       cfg.USE_FASTREID = True
>   else:
>       cfg.USE_FASTREID = False
> ```

in this file, it include a module named 'fastreid', so even if you do not set argument for fastreid, it also can't find this fastreid.

**Comment by susuhu** [comment]
> > > Because fastreid is used in the files **init**.py, deep_sort.py and feature_extractor.py, and these three files are in deep_sort folder. So, if you comment out all the codes about fastreid in these three files, the error will be solved.
> > 
> > 
> > but shouldn't below code in deepsort.py skip fastreid when I don't set arguments for --fastreid?
> > ```python
> >   if args.fastreid:
> >       cfg.merge_from_file(args.config_fastreid)
> >       cfg.USE_FASTREID = True
> >   else:
> >       cfg.USE_FASTREID = False
> > ```
> 
> in this file, it include a module named 'fastreid', so even if you do not set argument for fastreid, it also can't find this fastreid.

I see and problem solved. Thank you. 

One more question:  should the code be modified somehow to avoid manual comment out since it offers FASTREID as optional? But I'll close it for now.

**Comment by deeplearningers** [comment]
great!
