### ISSUE TITLE
您好，请问你的fps是多少？

### ISSUE THREAD

**Issue by DeepDuke** [ZQPei/deep_sort_pytorch#24]
你好！我用你的代码跑了个video，但是帧率只有大概6fps，效果看起来不是很好。我用的显卡是1080Ti。对了，请问可以使用yolov3-tiny的权重放入YOLO文件夹嘛？

**Comment by SpyderXu** [comment]
你可以修改下特征提取部分，代码中一次前向传播只为一个目标提取特征，你可以把一张图中的所有的目标攒成一个batch，然后一起前向传播，速度应该会快一些。

**Comment by SpyderXu** [comment]
> 你好！我用你的代码跑了个video，但是帧率只有大概6fps，效果看起来不是很好。我用的显卡是1080Ti。对了，请问可以使用yolov3-tiny的权重放入YOLO文件夹嘛？

你可以修改下特征提取部分，代码中一次前向传播只为一个目标提取特征，你可以把一张图中的所有的目标攒成一个batch，然后一起前向传播，速度应该会快一些

**Comment by ZQPei** [comment]
> 帧率只有大概6fps

你可以发现YOLO v3的代码全是基于python，主要是在检测阶段速度比较慢。
要加速很简单，把YOLO v3代码换成其他更快的版本，速度会明显提高。当然 @SpyderXu 提到的也是一个不错的方法。使用yolov3-tiny需要修改模型参数，肯定是可以的。
这个仓库只是一个demo，用作参考，仍需要修改，之后我会继续改进。
感谢你的建议！

**Comment by ZQPei** [comment]
> > 你好！我用你的代码跑了个video，但是帧率只有大概6fps，效果看起来不是很好。我用的显卡是1080Ti。对了，请问可以使用yolov3-tiny的权重放入YOLO文件夹嘛？
> 
> 你可以修改下特征提取部分，代码中一次前向传播只为一个目标提取特征，你可以把一张图中的所有的目标攒成一个batch，然后一起前向传播，速度应该会快一些

目前已经改过来了，感谢你的建议~
