### ISSUE TITLE
用Mars数据集训练的模型，怎么验证其accuracy?

### ISSUE THREAD

**Issue by sss-yyy** [ZQPei/deep_sort_pytorch#27]
Mars数据集中,Train的数据集和Test的数据集的标签不一样，怎么验证训练出来的模型在Test数据集上的Accuracy?

**Comment by ZQPei** [comment]
MARS数据集中每个人的图片都很多，你可以把train分成训练和测试来验证分类的acc

**Comment by china56321** [comment]
> MARS数据集中每个人的图片都很多，你可以把train分成训练和测试来验证分类的acc

MARS数据集好大啊，我看了bbox_train中有近510000张图片，bbox_test有近600000张，训练了3天，才跑了9 个epoch .  acc才0.3%,请问这是不是有问题啊？ 这样训练下去得花多少天啊

**Comment by china56321** [comment]
> Mars数据集中,Train的数据集和Test的数据集的标签不一样，怎么验证训练出来的模型在Test数据集上的Accuracy?

你好，我现在用deep_sort训练MARS数据集，acc好低啊。而且训练速度也慢，你说Train的数据集和Test的数据集的标签不一样，是哪里不一样？现在解决这个问题了吗？怎么解决的？
