### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by moyan007** [ZQPei/deep_sort_pytorch#3]
I'm so sorry to ask you for help owing to the error I got during the study of your code. Can you help me with that,please? Thanks a lot
Traceback (most recent call last):
  File "demo_yolo3_deepsort.py", line 68, in <module>
    det.detect()
  File "demo_yolo3_deepsort.py", line 42, in detect
    outputs = self.deepsort.update(bbox_xywh, cls_conf, im)
  File "/home/gongyuan/Downloads/DEMO/deep_sort_pytorch-master/deep_sort.py", line 25, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "/home/gongyuan/Downloads/DEMO/deep_sort_pytorch-master/deep_sort.py", line 66, in _get_features
    features = np.stack(features, axis=0)
  File "/home/gongyuan/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 349, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by ZQPei** [comment]
This is because there is no person detected in your video.
Now I have fixed this problem.
Thank you for pointing out this error!

**Comment by moyan007** [comment]
> This is because there is no person detected in your video.
> Now I have fixed this problem.
> Thank you for pointing out this error!

I use try... except... method to skip the error. But it seems that the princple of the way is not good enough. Can you share with me your method?

**Comment by ZQPei** [comment]
> I use try... except... method to skip the error. But it seems that the princple of the way is not good enough. Can you share with me your method?
I have refreshed deep_sort.py. you can download deep_sort.py from this repository again.
This bug occurs if np.stack() takes an empty list as a parameter, which means features is an empty list in line 66 in deep_sort.py.
So you can replace line 66 
`features = np.stack(features, axis=0)`
by adding a condition
```python
if len(features):
    features = np.stack(features, axis=0)
else:
    features = np.array([])
```
If you use try - except , the right code should be
```python
try:
    features = np.stack(features, axis=0)
except ValueError:
    features = np.array([])
```
That's it!
