### ISSUE TITLE
请问train代码是否使用 cosine metric learning

### ISSUE THREAD

**Issue by EternityZY** [ZQPei/deep_sort_pytorch#31]
非常感谢您的工作，对我非常有帮助。
想详细的请教您一下，在这版代码中，是否支持原作者DeepSort的训练方式， cosine metric learning？这个度量学习方式是一种不错的训练方法，请问您这版代码训练过程中是使用的这个算法训练的吗？

**Comment by ZQPei** [comment]
网络是分类网络，使用CE损失训练，特征匹配的时候是用的cosine metric。

**Comment by EternityZY** [comment]
> 网络是分类网络，使用CE损失训练，特征匹配的时候是用的cosine metric。

感谢您的回复，但是通过实验我发现，无论两个人体目标是否相似，甚至明显不同的两个物体，使用本仓库源码中的外观模型提取特征，再利用余弦距离求得的距离相似度始终为0.03-0.01左右。我使用的是您提供的模型。这个模型是否有效呢？是否需要重新训练？

**Comment by ZQPei** [comment]
是的，这个模型只是一个demo，建议你重新训练

**Comment by EternityZY** [comment]
> 是的，这个模型只是一个demo，建议你重新训练

感谢您的帮助！
