### ISSUE TITLE
是否有必要每帧都做检测？

### ISSUE THREAD

**Issue by yingsen1** [ZQPei/deep_sort_pytorch#37]
我知道deepSort比Sort算法多了ReID的模型，在关联跟踪框和检测框时多了一个指标。但是每帧检测+ReID速度只能达到10FPS左右（RTX2080TI），想请问下可以实现隔帧做检测吗？代码中哪一部分需要做修改？

**Comment by jacksonly** [comment]
我个人觉得如果想要提升fps的话，可以结合光流法（optical flow）的方法来减少detection次数。这个是在detection in video里面用的比较多的，比较经典的方法有CVPR’18的
Toward High Performance Video Object Detection (PDF:http://openaccess.thecvf.com/content_cvpr_2018/papers/Zhu_Towards_High_Performance_CVPR_2018_paper.pdf 中文解析：https://zhuanlan.zhihu.com/p/37068429)
。这个工作相当于直观上减少你问题里的detection次数，但是本身光流法就是一种追踪物体的方法，那么使用光流法生成的bounding box本身就应该带有前一帧的id信息。所以这种方法也可以减少了reid bounding box的次数。他们有开源的code，你可以测试一下

**Comment by yingsen1** [comment]
谢谢。
