### ISSUE TITLE
How can I make the detecting and tracking faster? 

### ISSUE THREAD

**Issue by aalzooke** [ZQPei/deep_sort_pytorch#38]
Is there any way to make it more faster?

**Comment by ZQPei** [comment]
Yes, you can make it more faster by doing the following:
1. Replace detector YOLOv3 code by a faster version. This Implemention of yolov3 is slow.
2. Set batch size larger than 1.
3. Try accelerate with TensorRT if you use nvidia GPU.
etc..

**Comment by aalzooke** [comment]
@ZQPei Can you please edit the code and make it faster, i'm new in python 
thank you

**Comment by ZQPei** [comment]
Sure, I am considering about that. But not today, maybe this weekend.
Hope this repo will help you.

**Comment by aalzooke** [comment]
@ZQPei sounds good, please add me on skype aalzooke

**Comment by aalzooke** [comment]
I hope you can make the speed over **20 FPS**

**Comment by ZQPei** [comment]
It also depends on the gpu you use.

**Comment by aalzooke** [comment]
I have NVIDIA Titan RTX, here' the photo of the test running the demo video 
Please imporve the speed, this's very important project 

<img width="427" alt="Screen Shot 2019-07-21 at 11 43 54 PM" src="https://user-images.githubusercontent.com/14840496/61605004-a853da80-ac11-11e9-877b-e6893d20e833.png">
