### ISSUE TITLE
A bug in feature extractor?

### ISSUE THREAD

**Issue by yingsen1** [ZQPei/deep_sort_pytorch#39]
https://github.com/ZQPei/deep_sort_pytorch/blob/5dd84c0cf331f9425c80e6eef54a11850d57d37c/deep/feature_extractor.py#L20
CV2读取的图像数值范围是0-255
这里应该需要将数值缩放到0-1
因为后面做一个标准化时用的是0-1的范围？
请问下/255这个是不是不应该注释？？

**Comment by ZQPei** [comment]
是的，已经修改过来了~
