### ISSUE TITLE
Usage: python demo_yolo3_deepsort.py [YOUR_VIDEO_PATH]

### ISSUE THREAD

**Issue by 201814476285951** [ZQPei/deep_sort_pytorch#40]
My video_path should where to change or add?

**Comment by crazylazydboy** [comment]
Hi, @201814476285951 Sorry for bothering you on already closed question.. Were you able run this repo on a video ??

I just want to run a simple video on this but..
after I updated this `self.vdo = cv2.VideoCapture('MyVideo.avi')` and it's still asking me for VIDEO_PATH
