### ISSUE TITLE
Can you add some details about train.py and data to README.md?Thanks a lot.

### ISSUE THREAD

**Issue by 201814476285951** [ZQPei/deep_sort_pytorch#41]
@ZQPei 
==================================== ERRORS ====================================
__________________________ ERROR collecting train.py ___________________________
train.py:44: in <module>
    torchvision.datasets.ImageFolder(train_dir, transform=transform_train),
../../anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/datasets/folder.py:178: in __init__
    target_transform=target_transform)
../../anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/datasets/folder.py:79: in __init__
    "Supported extensions are: " + ",".join(extensions)))
E   RuntimeError: Found 0 files in subfolders of: /home/ying/centerNet-deep-sort-master/deep/data/train
E   Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.49 seconds ============================
Process finished with exit code 0

**Comment by ZQPei** [comment]
Sure, Thanks for your advise!
BTW, Your problem can be found here #7
You will need reorgnize your image folders.

**Comment by pvtien96** [comment]
Yes, this dialogue really helps. tks.
