### ISSUE TITLE
: cannot connect to X server localhost:10.0？？

### ISSUE THREAD

**Issue by bassyess** [ZQPei/deep_sort_pytorch#45]
When I run the demo_yolo3_deepsort program under linux, this error occurs: Can not connect to X server localhost: 10.0, I have commented out the cv2.imshow() function in the source code, or reported the same error, and what else needs to be modified?

**Comment by ZQPei** [comment]
The reason is that you run it on a server, and default ssh dont support X server.
You can add `--ignore_display` at the end of your command.
The results will be saved to `demo.avi` by default or you can specify save path by add `--save_path`.
