### ISSUE TITLE
suggestion on skip detection for a speed-up?

### ISSUE THREAD

**Issue by rambleramble** [ZQPei/deep_sort_pytorch#47]
Great work, thanks a lot for sharing the code!

Could you give some suggestions on how to modify the code if to skip detection for every n frames, say n=3?
The purpose is to save the detection time for every frame, which might not be needed.

It seems that the [line](https://github.com/ZQPei/deep_sort_pytorch/blob/37a32806ccab51a6a872ad0c13c9c8add80690d4/deep_sort/deep_sort.py#L40)
will effectively become the following:
self.tracker.update([])
will your deep_sort support this?

Thanks again!

Thanks.

**Comment by ZQPei** [comment]
I have add an argument `frame_interval` to support this.
Have a try.

**Comment by sampathkethineedi** [comment]
@rambleramble Did you try this approach - ```self.tracker.update([])  if idx_frame % n != 0```

**Comment by sampathkethineedi** [comment]
The deepsort tracker doesn't really track without detection. So if the interval is more than 3, box stays back in previous position. This affects the identity assignment based on features
