### ISSUE TITLE
ckpt.t7's Training Data

### ISSUE THREAD

**Issue by xjinchuan** [ZQPei/deep_sort_pytorch#50]
Which dataset that ckpt.t7(download from https://drive.google.com/drive/folders/1xhG0kRH1EX5B9_Iz8gQJb7UNnn_riXi6) is training on?

**Comment by ZQPei** [comment]
Market1501

**Comment by xjinchuan** [comment]
Thank you. And which dataset that yolov3 is training on?

**Comment by ZQPei** [comment]
coco.
The parameter of yolov3 is the same as paper.

**Comment by totoadel** [comment]
how to train my  ckpt.t7 in another objects like animals
