### ISSUE TITLE
NMS with threshold 1.0?

### ISSUE THREAD

**Issue by wlguan** [ZQPei/deep_sort_pytorch#54]
Hi, thanks for your excellent job. But I don't quite understand the purpose of NMS here, where self.nms_max_suppression==1, it seems like a pure np.argsort operation. Could you explain this a bit?
indices = non_max_suppression( boxes, self.nms_max_overlap, scores)

**Comment by ZQPei** [comment]
It is because the official deepsort code set `self.nms_max_suppression==1`.
If `nms_max_suppression==1`, it means no nms at all.
Now I have add this super parameter to `configs/deepsort.yaml`, you can change it for a better tracking.
