### ISSUE TITLE
train error 

### ISSUE THREAD

**Issue by Vincent630** [ZQPei/deep_sort_pytorch#55]
i trained this model as the readme but when it run over the first epoch it interrupt and report this error ,can you help me with this problem,i will appreciate it so much.

/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_u                                                                       pdateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, in                                                                       t, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0]                                                                        Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.c line=36 error=5                                                                       9 : device-side assert triggered
Traceback (most recent call last):
  File "deep/train.py", line 191, in <module>
    main()
  File "deep/train.py", line 184, in main
    test_loss, test_err = test(epoch)
  File "deep/train.py", line 124, in test
    test_loss += loss.item()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch                                                                       /aten/src/THC/generic/THCStorage.c:36

**Comment by crazylazydboy** [comment]
@Vincent630 If you were successful in training using train.py, Can you help me with the following error..

`Segmentation fault (core dumped)`

**Comment by chinmayjog13** [comment]
@Vincent630 did you solve your issue? I too ran into the same problem with mars

**Comment by yustaub** [comment]
@chinmayjog13 @Vincent630 I make the the count of train folder the same as test folder, and also this error, did u solve this problem?

**Comment by yustaub** [comment]
@Vincent630 @chinmayjog13 the test acc is very low , can u solve it?

**Comment by antoniolq** [comment]
I ran into the same problem with mars too, anyone can help me?
