### ISSUE TITLE
Training for Market1501

### ISSUE THREAD

**Issue by liaojiacai** [ZQPei/deep_sort_pytorch#59]
How to use the Market1501 dataset to train deep sort? After downloading the dataset, I found this dataset can't be loaded for training directly, can anyone give some specific instructions? Thanks in advance.

**Comment by liaojiacai** [comment]
@ZQPei Hi, did you have finished the training with Market1501? If possible, can you give some advice to training with Market1501 dataset, thanks!!!

**Comment by chinmayjog13** [comment]
@liaojiacai Did you get the solution? Can you please share?

**Comment by luvwinnie** [comment]
@liaojiacai hi do you now how to use the market1501 dataset?
