### ISSUE TITLE
Cannot detect from my own weight file

### ISSUE THREAD

**Issue by sandeshshrestha45** [ZQPei/deep_sort_pytorch#6]
Hello ZQPei,
When i run the demo with the available yolov3 original weight file and cfg file, it works perfectly. But when i use my custom trained weight file and cfg file,  it doesnot detect anything. What might be the problem?

**Comment by ZQPei** [comment]
Your custom weight file and cfg file of yolov3?
You might need to change this forward yolov3 scripts, because this yolov3 is only a demo.
I am curious that if you detect nothing, why there is no Error?
I need more details to tell you what the problem might be.

**Comment by sandeshshrestha45** [comment]
I trained yolov3 using my own datasets which has 5 classes including humans. I have generated weight file from it. I replaced the original weight file with the one i generated from my datasets. Actually I am getting detections when i run it on darknet but when i use your repo, i dont get any detections. I downloaded the deep sort checkpoint file too placed it inside checkpoint folder following your instructions. Then when i try it with original yolov3 weight, it is showing detections and tracking but when i try it with my own weight file, it doesnt detect anything.

**Comment by ZQPei** [comment]
I think the problem is that, in the dataset of yours the Human class id may not be 0.
See the code in demo.py, line 37-39.
```python
            if bbox_xywh is not None:
                mask = cls_ids==0
                bbox_xywh = bbox_xywh[mask]
```
It only choose the cls_ids equals to 0.

**Comment by sandeshshrestha45** [comment]
it worked. thanks a lot.

**Comment by duyao-art** [comment]
@sandeshshrestha45  Hello. I got the same problem now.  I am wondering if we just only change the position of person label to  0, there is no doubt that  the deep_sort can track the person. but how about other classes that we want to detect and track? How should we do that? I am confused about that. I hope you could give me some advice . thank you
