### ISSUE TITLE
这个怎么同时跟中多个类呀？

### ISSUE THREAD

**Issue by xiaoliyong** [ZQPei/deep_sort_pytorch#64]

**Comment by jhxing** [comment]
只需要修改主程序demo_yolo3_deepsort.py中line57:
`mask = cls_ids==0` 
这里的0 表示的是coco类别的‘person’,你可以根据你的需求修改类别，比如我想要同时追踪人和各种车辆，就修改为了：
`mask = cls_ids < 8`
另外./YOLOv3/cfg/coco.names 可以查看类别对应的序号，现附如下：
`person
bicycle
car
motorbike
aeroplane
bus
train
truck
boat
traffic light
fire hydrant
stop sign
parking meter
bench
bird
cat
dog
horse
sheep
cow
elephant
bear
zebra
giraffe
backpack
umbrella
handbag
tie
suitcase
frisbee
skis
snowboard
sports ball
kite
baseball bat
baseball glove
skateboard
surfboard
tennis racket
bottle
wine glass
cup
fork
knife
spoon
bowl
banana
apple
sandwich
orange
broccoli
carrot
hot dog
pizza
donut
cake
chair
sofa
pottedplant
bed
diningtable
toilet
tvmonitor
laptop
mouse
remote
keyboard
cell phone
microwave
oven
toaster
sink
refrigerator
book
clock
vase
scissors
teddy bear
hair drier
toothbrush`

祝好

**Comment by ZQPei** [comment]
@jhxing 感谢回复。
另外说一下，如果要跟踪多个类，可能会非常不准确。因为deepsort中的reid模型是用的行人数据集来训练的！最好再跟踪其他类别之前，先训练其他类别的reid模型。

**Comment by duyao-art** [comment]
@jhxing 答主你好，我自己的data.names里面有六个类别，所以我将这里改成了<6.但是run yolov3_deepsort.py之后，detection number和tracking number仍然一直为零。我就很郁闷。我在单独的yolov3 工程中用相同的cfg,和我自己又训练的权重，就可以得到检测的结果。
答主能够给一些可能出现问题的建议呢？谢谢

**Comment by jhxing** [comment]
> @jhxing 答主你好，我自己的data.names里面有六个类别，所以我将这里改成了<6.但是run yolov3_deepsort.py之后，detection number和tracking number仍然一直为零。我就很郁闷。我在单独的yolov3 工程中用相同的cfg,和我自己又训练的权重，就可以得到检测的结果。
> 答主能够给一些可能出现问题的建议呢？谢谢

您好，关于您的问题我没有遇到过，不过您需要确认一下您在训练模型的时候，所用的类别和数字的对应关系是否正好是0-7；或者，您可以在调试的时候输出一下cls_ids这个变量，查看其具体数值是否和期望的0-7一致，希望对您有所帮助。

**Comment by duyao-art** [comment]
好的好的，谢谢啦～   感谢帮助和建议


jhxing <notifications@github.com> 于2020年6月2日周二 上午11:44写道：

**Comment by starsky68** [comment]
@jhxing  @ZQPei 
答主你好，假设我们有50个类，但是我们只对其中的3，4，5，8，9，10跟踪，其他的做检测，那么，mask = cls_ids < a，其中的a就是我要进行跟踪的总数吗？比如此处为a=6，然后在使用deepsort训练reid模型的时候只对这六类进行训练，得到最终的reid权重就可以了对吧，然后自制数据集的时候，多类别的数据集如何制作？可否详细的给一些经验，感激不尽。

**Comment by starsky68** [comment]
多个类别的话，reid是不是多个向量的组合，如果是多个向量组合在一起的矩阵，直接送到后面进行跟踪，这合理吗？
@ZQPei @jhxing

**Comment by JAYCHOU2020** [comment]
> @jhxing 答主你好，我自己的data.names里面有六个类别，所以我将这里改成了<6.但是run yolov3_deepsort.py之后，detection number和tracking number仍然一直为零。我就很郁闷。我在单独的yolov3 工程中用相同的cfg,和我自己又训练的权重，就可以得到检测的结果。
> 答主能够给一些可能出现问题的建议呢？谢谢

你deepsort的标签文件是什么格式的啊能看看吗，一直不知道如何训练自己的deep sort模型......万分感谢！
