### ISSUE TITLE
multi-class tracker?

### ISSUE THREAD

**Issue by albertchristianto** [ZQPei/deep_sort_pytorch#66]
hi, @ZQPei.
thank you for sharing your work and this is a great repo.
I want to build multi-class tracker using your repo.
Can you give a suggestion which part of the code which is responsible with checking between new detected object and tracked object? 
Thank you in advance.

best regards,
Albert Christianto

**Comment by crazylazydboy** [comment]
Hi, How did you run this repo on a video ?? What needs to be added and where ??

**Comment by albertchristianto** [comment]
hi, @crazylazydboy.
first you can add yolov3 or other detector, then detect the object each frame. and use this repo to track the trajectory.

**Comment by crazylazydboy** [comment]
@albertchristianto ,

This one already has yolov3, right ? It's already on the repo
Can you please explain it to me how did you run this ??

**Comment by crazylazydboy** [comment]
I just want to run a simple video on this but..
after I updated this `self.vdo = cv2.VideoCapture('MyVideo.avi')` and it still ask me for VIDEO_PATH

**Comment by albertchristianto** [comment]
rather than making changes to the code, try to run this command

python3 demo_yolo3_deepsort.py MyVideo.avi

the error is happened because the argparse code can't find the input.

**Comment by crazylazydboy** [comment]
Thanks for the reply @albertchristianto 
It totally works.. 
Do you have any idea how to use this on **http** or **rtsp** online streams.. argparse returns error
`Assertion Error: Error: path error`

**Comment by crazylazydboy** [comment]
Don't worry.. I just commented every code with `VIDEO_PATH` gave my rtsp link manually to 
`self.vdo = cv2.VideoCapture('rtsp://......'`)` and it works..
