### ISSUE TITLE
您好，我想请问如何更改reid存储的时间（消失时间小算遮挡，消失时间大算离开）

### ISSUE THREAD

**Issue by 17702513221** [ZQPei/deep_sort_pytorch#68]

**Comment by ZQPei** [comment]
修改`deep_sort/sort/tracker.py`下面的`max_age`。
Attributes
    ----------
    metric : nn_matching.NearestNeighborDistanceMetric
        The distance metric used for measurement to track association.
    max_age : int
        Maximum number of missed misses before a track is deleted.
    n_init : int
        Number of frames that a track remains in initialization phase.
    kf : kalman_filter.KalmanFilter
        A Kalman filter to filter target trajectories in image space.
    tracks : List[Track]
        The list of active tracks at the current time step.
