### ISSUE TITLE
Why ''im = ori_im'' ？

### ISSUE THREAD

**Issue by chaipangpang** [ZQPei/deep_sort_pytorch#71]
Hi, Thanks for your great work.
I have some issues with image pre-processing:
```python
            _, ori_im = self.vdo.retrieve()  
            im = cv2.cvtColor(ori_im, cv2.COLOR_BGR2RGB)  
            im = ori_im  
```
Why is it like this? 'cv2.cvtColor' is worked?
Thank you!

**Comment by ZQPei** [comment]
Thank you. It is my mistake.
I have fixed this error.
