### ISSUE TITLE
cuda runtime error

### ISSUE THREAD

**Issue by szh91** [ZQPei/deep_sort_pytorch#72]
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:74

**Comment by crazylazydboy** [comment]
Did you try updating CUDA Drivers ?  What kind of environment are you running this in ?

**Comment by szh91** [comment]
yes, I have tried to update the version of cuda drivers, but it still doesn't work, My cuda is 8.0, cudnn: 6.0， gcc: 5.4

**Comment by crazylazydboy** [comment]
my cuda toolkit is version **9.0** and cudnn is version **7.1.2**.. Maybe try that.

**Comment by ZQPei** [comment]
@crazylazydboy Thank you for your answer!

@szh91 
I suggest you do the following things.
1. Update this repo by `git pull origin master`.
2. Add `--cpu` to use cpu for tracking for a quick start.
3. If you insist to use gpu, run `torch.cuda.is_available()` to check your pytorch is cuda supportable.
If `torch.cuda.is_available()` is `False`, please go to [pytorch official site](www.pytorch.org) and download the right version of pytorch to match your cuda version.
