### ISSUE TITLE
Error using test.py with MARS dataset + Need clarification on train.py

### ISSUE THREAD

**Issue by crazylazydboy** [ZQPei/deep_sort_pytorch#73]
@ZQPei @sandeshshrestha45 @nakhonsoft @silymarins @harshsp31 @akshitac8 @EternityZY @liaojiacai @doorteeth @xjinchuan @201814476285951 @yingsen1 @JieChen91 @ujsyehao @dibyadas @wsuny @moyan007 @adouwitti @hyperfraise @SpyderXu

Hi, I've successfully trained the deep_sort_pytorch model with MARS dataset. Here are the results. Feel free to comment if you have any advice for improvement.

![Screenshot from 2019-12-17 09-40-45](https://user-images.githubusercontent.com/40971348/70961700-20390a80-20b5-11ea-8e95-76219e99e7af.png)

![train](https://user-images.githubusercontent.com/40971348/70961673-0c8da400-20b5-11ea-9bb0-3fffdc94bdf4.jpg)

But I am having trouble with test.py. Here's the error.

![Screenshot from 2019-12-17 09-50-00](https://user-images.githubusercontent.com/40971348/70962111-870af380-20b6-11ea-8fb4-c5a8564e1da5.png)

I've tried the follwing fix as well but to no avail.

`self.net = Net(num_classes=1261, reid=True)`

**Comment by housz77** [comment]
Hello, I have problems in training the deep_sort_pytorch model with MARS dataset. 

The problem is the following:
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "e:/housz/deep_sort_pytorch/deep_sort/deep/train.py", line 196, in <module>
    main()
  File "e:/housz/deep_sort_pytorch/deep_sort/deep/train.py", line 189, in main
    test_loss, test_err = test(epoch)
  File "e:/housz/deep_sort_pytorch/deep_sort/deep/train.py", line 129, in test
    test_loss += loss.item()
RuntimeError: CUDA error: device-side assert triggered

I would appreciate it if you can give me any advice.
Thank you very much.

**Comment by crazylazydboy** [comment]
@ZQPei can you help fix this error ?

**Comment by ZQPei** [comment]
Looks like the number of classes dismatch when testing.
Go to line 45 in `deep/test.py` and replace the line with the following.
```python
net.load_state_dict(net_dict, strict=False)
```

This should work. If it doesnot, we can discuss later.

**Comment by crazylazydboy** [comment]
@ZQPei I will try that. What do you think about my **top1err** and **loss** ? Why the sudden drop after 20 epoch ?

**Comment by ZQPei** [comment]
The sudden drop of loss is caused by the drop of learning rate.

**Comment by crazylazydboy** [comment]
@ZQPei  Will it affect performance of the net ? How did you prevent it ?

UPDATE: Sorry, you fix didn't work.. Error popped up again..

**Comment by ZQPei** [comment]
Tell me more information.
What is the error now?

**Comment by crazylazydboy** [comment]
@ZQPei Should I update to **update 1-1-2020**.. Did you improve significantly ?

**Comment by ZQPei** [comment]
I just made the detection part more faster and refactored my code.
How about replacethe line `net=Net(reid=True)` with `net=Net(reid=True,num_classes=1261`?

**Comment by crazylazydboy** [comment]
@ZQPei I wiil try that. I noticed a new requirement **vizer** and new instructions **Compile nms module**. Can you explain what it does ?

**Comment by crazylazydboy** [comment]
@ZQPei  It worked !! 

But there's a new error in **evaluate.py** Did I put too much images for test.py ?

![Screenshot from 2020-01-01 15-24-52](https://user-images.githubusercontent.com/40971348/71639555-36e18300-2cab-11ea-9124-6145d59dc2ee.png)

**Comment by ZQPei** [comment]
Maybe. Out of memory.

**Comment by crazylazydboy** [comment]
@ZQPei Ok, I will try with less images. Can you explain new requirement **vizer** and new instruction **Compile nms module** ??

**Comment by ZQPei** [comment]
I add a faster version of nms module written by c++.
vizer is a tool for draw bboxes.

**Comment by crazylazydboy** [comment]
I get **top1Accuracy of 0.000**.. However your original **ckpt.t7** also gets **top1Accuracy of 0.000**

 Is your code working OK ? Or Is my query & gallery configuration wrong ??

**Comment by ZQPei** [comment]
Maybe you can check your query & gallery configuration.

**Comment by crazylazydboy** [comment]
@ZQPei I did as you said.. Take each class with a total of N images, Move **2N/3** of them to **query**,  Put **N/3** (the rest) to **gallery**.  How did you do it?

**Comment by tangsipeng** [comment]
@crazylazydboy  Did you know how to make query and gallery data  on market1501?

**Comment by crazylazydboy** [comment]
@tangsipeng I have already described how I sorted classes into two folders in the above comment. It is same for any dataset..

**Comment by tangsipeng** [comment]
@crazylazydboy  my Directory Structure：
![TIM截图20200108163933](https://user-images.githubusercontent.com/4188431/71962949-930d4f80-3235-11ea-9049-f47fdd189379.jpg)
i want to test ‘ckpt.t7’ at Market-1501
i put images of “bounding_box_test” into “gallery” 
and put images of “query” into “query”
and both  of “gallery” and “query” have same  classes
but when i run test.py and evaluate.py , i got
Acc top1:0.000

**Comment by crazylazydboy** [comment]
@tangsipeng I have the same issue. I have notified @ZQPei about it. He is yet to respond..

**Comment by tangsipeng** [comment]
@crazylazydboy i found what's wrong
i comments this line
![image](https://user-images.githubusercontent.com/4188431/72047158-daa6e080-32f4-11ea-9655-f67b78d6bbb1.png)
and got 
Acc top1:0.993

here's my code of dataset changing
`import re
import os
import shutil
 
def extract_market(src_path, dst_root):
    img_names = os.listdir(src_path)
    pattern = re.compile(r'([-\d]+)_c(\d)')
    pid_container = set()
    for img_name in img_names:
        if '.jpg' not in img_name:
            continue
        print(img_name)
        # pid: 每个人的标签编号 1
        # _  : 摄像头号 2
        pid, _ = map(int, pattern.search(img_name).groups())
        # 去掉没用的图片
        if pid == 0 or pid == -1:
            continue
        dst_dir = os.path.join(dst_root, str(pid))
        if os.path.exists(dst_dir) == False:
            os.makedirs(dst_dir)
        shutil.copy(os.path.join(src_path, img_name), os.path.join(dst_dir, img_name))
        
if __name__ == '__main__':
    #dst_root = '/home/tangsipeng/mot/reid/reid-strong_bl/bak/tsp_market1501/gallery'
    #src_path = '/home/tangsipeng/mot/reid/reid-strong_bl/bak/Market-1501-v15.09.15/bounding_box_test'
    dst_root = '/home/tangsipeng/mot/reid/reid-strong_bl/bak/tsp_market1501/query'
    src_path = '/home/tangsipeng/mot/reid/reid-strong_bl/bak/Market-1501-v15.09.15/query'
    extract_market(src_path, dst_root)
`

**Comment by tangsipeng** [comment]
@crazylazydboy 
i found what's wrong
i comments this line
![image](https://user-images.githubusercontent.com/4188431/72047476-8ea86b80-32f5-11ea-9320-7f98468c3fbd.png)

and got
Acc top1:0.993

here's my code of dealing dataset of market1501

[chg_market1501data_to_test.txt](https://github.com/ZQPei/deep_sort_pytorch/files/4039197/chg_market1501data_to_test.txt)

**Comment by yustaub** [comment]
@crazylazydboy @tangsipeng @ZQPei the test acc is very low when I run the train.py, can u help solve it?
![image](https://user-images.githubusercontent.com/40256410/74607069-6c81e480-5110-11ea-9b1b-32f59c91d9f3.png)

**Comment by cydiachen** [comment]
hello, would you mind providing more details about improving the accuracy of testset

**Comment by china56321** [comment]
> @crazylazydboy @tangsipeng @ZQPei the test acc is very low when I run the train.py, can u help solve it?
> ![image](https://user-images.githubusercontent.com/40256410/74607069-6c81e480-5110-11ea-9b1b-32f59c91d9f3.png)

Have you solved the problem ? i also encountered this problem,It is not only low in accuracy, but also very slow in training speed.

**Comment by SmallMunich** [comment]
@china56321 you should split the mars datasets of bbox_train with two components. bbox_train to bbox_train_part & bbox_train_val folders. the split code can refer to the following code:

`import os
import random
import shutil

def moveFile(fileDir, dstDir, rate):

    pathDir = os.listdir(fileDir)
    file_number = len(pathDir)

    dstDir = dstDir + fileDir[-4:]
    if not os.path.isdir(dstDir):
        os.mkdir(dstDir)

    pick_number = int(file_number*rate)
    sample = random.sample(pathDir, pick_number)

    for name in sample:
        shutil.move(fileDir+'/'+name, dstDir+'/'+name)

    return

def mars_train_val(train_path, dst_path, rate):

    for root, dirs, files in os.walk(train_path, topdown=True):

        if root == train_path:
            continue
        moveFile(root, dst_path, rate)


if __name__ == '__main__':

    # 在bbox_train同级目录下新建一个bbox_val文件夹
    train_path = "/home/ubuntu/Data/Mars/bbox_train/"
    dst_path = "/home/ubuntu/Data/Mars/bbox_val/"
    if not os.path.isdir(dst_path):
        os.mkdir(dst_path)

    mars_train_val(train_path, dst_path, 0.2)`


then, you can train it will find the test acc :smile: .
