### ISSUE TITLE
Reduce detection operations and maintaining a count.

### ISSUE THREAD

**Issue by nik9hil** [ZQPei/deep_sort_pytorch#74]
1. Having some issues while reducing the number of frames processed by YOLOv3 detector. Wanted to do so in order to speed up the performance. Do we have to use detector for each and every frame? Can't we use detector only for, say every 2nd frame and use DeepSort for each frame?
eg. https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/ , here, they're not using detector for each and every frame.
Please suggest some method. 

2. How to maintain the number of people crossing, a particular line (say, y = c)? I have used the y of bounding box and checking if it is exceeding c. Is there a better method out there?

**Comment by ZQPei** [comment]
1. I have add an argument `frame_interval` to allow you to detect once for each k frames.
2. How about use the center coordinate to judge crossing?

**Comment by sampathkethineedi** [comment]
@ZQPei ```frame_interval``` skips the entire process on the frame. Can we skip just the detection for say 10 frames and rely on tracking only?
