### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by DerekSunYH** [ZQPei/deep_sort_pytorch#76]
你好 我运行程序检测视频中的目标时，无法调用GPU，GPU占用率为0%，我是1080ti的显卡。（我把您原来程序中的只检测人换成了只检测car）。不知您是否知道为什么。

**Comment by ZQPei** [comment]
pytorch和cuda版本不对的问题吧。你看看`torch.cuda.is_available()`是否是True。

**Comment by DerekSunYH** [comment]
是true，我也很奇怪，我把cuda的地方都打印出来，显示的都是true并且device都是cuda。所以只有可能是cuda版本和pytorch版本不一致的原因吗

**Comment by ZQPei** [comment]
这样的话，你用pdb调试一下，看看`use_cuda`是否是True

**Comment by DerekSunYH** [comment]
嗯 我试试  谢谢
