### ISSUE TITLE
OS and CUDA versions

### ISSUE THREAD

**Issue by CVH95** [ZQPei/deep_sort_pytorch#77]
Which OS and CUDA version are you using? And which fps rates can it achieve?

Also, I notice that it would help adding this two to `requirements.txt`, so that everything runs smoothly when installing from scratch in a `virtual environment`:

```sh
pyyaml
easydict
```

**Comment by ZQPei** [comment]
I use Ubuntu1604 and CUDA-10.0. 
17fps on 1080ti.

Thanks for your advice! I have add these two packages in `requirements.txt` now.

**Comment by loveunk** [comment]
> I use Ubuntu1604 and CUDA-10.0.
> 17fps on 1080ti.
> 
> Thanks for your advice! I have add these two packages in `requirements.txt` now.

17fps for YOLOv3? What's the resolution of the input video? Thanks.
