### ISSUE TITLE
ModuleNotFoundError: No module named 'vizer'

### ISSUE THREAD

**Issue by judytraj007** [ZQPei/deep_sort_pytorch#78]
When I run from utils.draw import draw_boxes to importing from utils, it throws the error, ModuleNotFoundError: No module named 'vizer'.
Removing the line **from vizer.draw import draw_boxes** from draw.py in utils directory fixes this. (line no: 3)

**Comment by ZQPei** [comment]
Thank you for you advice. I have fixed it.
