### ISSUE TITLE
Runtime Error : nms Not compiled with GPU support

### ISSUE THREAD

**Issue by crazylazydboy** [ZQPei/deep_sort_pytorch#79]
![Screenshot from 2020-01-03 20-59-06](https://user-images.githubusercontent.com/40971348/71727348-8de28600-2e6c-11ea-8470-1cccb3e8d018.png)

**Comment by crazylazydboy** [comment]
@ZQPei What seems to be the problem here ?

**Comment by ZQPei** [comment]
Please check your nvcc version is consistent with your CUDA version and gcc version >= 5.5.

**Comment by ZQPei** [comment]
If you have ` torchvision>=0.3`, it is OK to use `torchvision.ops.nms`.

**Comment by crazylazydboy** [comment]
@ZQPei, I have updated everything.. Still doesn't work.  

nvcc -- version   7.5.17
CUDA version 10.2
cudnn version 7.1.2
gcc --version 5.4.0

NOTE: I can still run the old code after updating everything

**Comment by ZQPei** [comment]
Try to rebuild the nms code. Remember to delete `ext/build` and `ext/torch_extension.*.so`.

**Comment by crazylazydboy** [comment]
Here's the build error.

![Screenshot from 2020-01-05 10-32-37](https://user-images.githubusercontent.com/40971348/71774761-e322b280-2fa6-11ea-8527-bd781c25250e.png)

**Comment by ZQPei** [comment]
There must be multiple CUDA versions on your device.
Check `torch.version.cuda` if it is consistent with `nvcc --version`.

**Comment by crazylazydboy** [comment]
How do I check `torch.version.cuda `??

**Comment by ZQPei** [comment]
`import torch; torch.version.cuda`

**Comment by crazylazydboy** [comment]
Yep, there was a previous installment along with the updated one.. Thanks for pointing out

**Comment by banana16314** [comment]
Hi, how do you deal with it? multiple cuda versions, one is 7.5, the other is 10.1.
