### ISSUE TITLE
How to change the class name and display all the classes? 

### ISSUE THREAD

**Issue by sandeshshrestha45** [ZQPei/deep_sort_pytorch#8]
Hello ZQPei,
What changes do I have to make in your code if I want to display all the classes with their class name? I have 5 classes. E.g. human, tv on, tv off, fan on and fan off. I need to display their names along with their respective object id. In your code, only persons are displayed by bounding box and it is labelled as 'object 1', 'object 2' and so on. If need to display as ' human 1', 'human 2', 'fan on 1', 'fan on 2' etc..... How can I do that?

**Comment by ZQPei** [comment]
If you want display as 'human 1', 'human2', you can replace 'object' to 'human' in `util.py` line 43.
Considering that your CNN model is trained only for human feature, for other classes, like fan or tv, you can remove the deep model and only use the sort algorithm to track them.

**Comment by sandeshshrestha45** [comment]
Actually I am trying to track only humans class.  I don't need to track  other classes. I only need to display them as a result of yolov3 detections. What changes should I make to do that?

**Comment by ZQPei** [comment]
```python
mask = cls_ids!=0
bbox_xywh = bbox_xywh[mask]
cls_conf = cls_conf[mask]
bbox_xyxy = torch.zeros_like(bbox_xywh, dtype=bbox_xywh.dtype)
bbox_xyxy[0] = bbox_xywh[:,0]-bbox_xywh[:,2]/2
bbox_xyxy[1] = bbox_xywh[:,1]-bbox_xywh[:,3]/2
bbox_xyxy[2] = bbox_xywh[:,0]+bbox_xywh[:,2]/2
bbox_xyxy[3] = bbox_xywh[:,1]+bbox_xywh[:,3]/2
ori_im = draw_bboxes(ori_im, bbox_xyxy, identities=None, offset=(xmin,ymin))
```
Add those before or after line 38-46 of demo.py.
You can have a try.

**Comment by sandeshshrestha45** [comment]
thank you. 👍

**Comment by sandeshshrestha45** [comment]
I am getting the following error.

![screenshot from 2019-03-05 14-07-13](https://user-images.githubusercontent.com/10694553/53787026-05dfd700-3f50-11e9-9dcf-d355ea3a4862.png)

This is the edited code.
[demo.txt](https://github.com/ZQPei/deep_sort_pytorch/files/2929677/demo.txt)

Can you please help me?

**Comment by ZQPei** [comment]
Change `torch.zeros_like` to `np.zeros_like`.

**Comment by sandeshshrestha45** [comment]
After changing torch.zeros_like to np.zeros_like, I got another error as follows:
![capture](https://user-images.githubusercontent.com/10694553/53791941-2d896c00-3f5d-11e9-92b1-f43e8e43f92e.PNG)

What could be the problem?
[demo_yolo3_deepsort2.txt](https://github.com/ZQPei/deep_sort_pytorch/files/2929982/demo_yolo3_deepsort2.txt)

**Comment by ZQPei** [comment]
```python
            if bbox_xywh is not None:
                mask = cls_ids==0
                bbox_xywh_human = bbox_xywh[mask]
                bbox_xywh_human[:,3] *= 1.2
                cls_conf_human = cls_conf[mask]
                outputs = self.deepsort.update(bbox_xywh_human, cls_conf_human, im)
                if len(outputs) > 0:
                    bbox_xyxy = outputs[:,:4]
                    identities = outputs[:,-1]
                    ori_im = draw_bboxes(ori_im, bbox_xyxy, identities, offset=(xmin,ymin))
                
                mask = np.where(cls_ids!=0)[0]
                bbox_xywh_other = bbox_xywh[mask]
                cls_conf_other = cls_conf[mask]
                bbox_xyxy = np.zeros_like(bbox_xywh, dtype=bbox_xywh.dtype)
                bbox_xyxy[:,0] = bbox_xywh[:,0]-bbox_xywh[:,2]/2
                bbox_xyxy[:,1] = bbox_xywh[:,1]-bbox_xywh[:,3]/2
                bbox_xyxy[:,2] = bbox_xywh[:,0]+bbox_xywh[:,2]/2
                bbox_xyxy[:,3] = bbox_xywh[:,1]+bbox_xywh[:,3]/2
                if(len(bbox_xywh_other)>0):
                    ori_im = draw_bboxes(ori_im, bbox_xyxy, None, offset=(xmin,ymin))
```

**Comment by sandeshshrestha45** [comment]
Thank you. Now how can i assign each detection by their own class name? If i change "object" into "human" in util.py, the it will show human for every class. How can i provide specfic class name to each detection?

**Comment by sandeshshrestha45** [comment]
Hello ZQPei,
Can you please help  me with this as well?

**Comment by ZQPei** [comment]
Quite busy these days.
You can add more parameters to function `draw_bbox` in `util.py`, like `cls_name` to denote specify class names.
If you want test videos with different resolution, you can comment `im = cv2.resize(...)` in demo.py.

**Comment by sandeshshrestha45** [comment]
I will try that. Thank you very much.
