### ISSUE TITLE
torchvision.transforms.Resize((128,64))

### ISSUE THREAD

**Issue by tangsipeng** [ZQPei/deep_sort_pytorch#83]
in test.py 
transform = torchvision.transforms.Compose([
    torchvision.transforms.Resize((128,64)),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
why  Resize((128,64)) ?  image shape in market1501 is 64 * 128

**Comment by ZQPei** [comment]
size arg matchs to (height, width).

```python
class Resize(object):
    """Resize the input PIL Image to the given size.

    Args:
        size (sequence or int): Desired output size. If size is a sequence like
            (h, w), output size will be matched to this. If size is an int,
            smaller edge of the image will be matched to this number.
            i.e, if height > width, then image will be rescaled to
            (size * height / width, size)
```
