### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by amitabduls15** [ZQPei/deep_sort_pytorch#88]
I have a problem when trying to compile the nms module, when I try to do sh build.sh I get an error message like this.
![Screenshot_2020-02-04_09-35-18](https://user-images.githubusercontent.com/38752309/73708703-af67b380-4731-11ea-8a65-ff8536f96b7d.png)

thanksss

**Comment by YuqingWu79** [comment]
i have this too!How did you deal with that?

**Comment by ZQPei** [comment]
The simpliest way to solve the NMS compiling error is to upgrade your torchvision to 0.3.x and pytorch to 1.1.
I suppose the error in your figure is either your gcc version too low or some library missing. 
You just upgrade your torchvision and avoid this compiling trouble.
