### ISSUE TITLE
运行时 报ipython错误

### ISSUE THREAD

**Issue by Scarlatt9** [ZQPei/deep_sort_pytorch#89]
/home/scarlett/work/code/my/deepsort/deep_sort_pytorch/utils/parser.py:24: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()), Loader=yaml.FullLoader)
Traceback (most recent call last):
  File "/home/scarlett/work/code/my/deepsort/deep_sort_pytorch/yolov3_deepsort.py", line 114, in <module>
    with VideoTracker(cfg, args) as vdo_trk:
  File "/home/scarlett/work/code/my/deepsort/deep_sort_pytorch/yolov3_deepsort.py", line 21, in __init__
    raise UserWarning("Running in cpu mode!")
UserWarning: Running in cpu mode!

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by ZQPei** [comment]
它提示你在用cpu跑了。
如果没有GPU的话，你就把`yolov3_deepsort.py`里面的19-20行删掉就可以了。

**Comment by Scarlatt9** [comment]
哦哦 谢谢啦 这个问题已解决&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pzq"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 晚上9:55
收件人: "ZQPei/deep_sort_pytorch"<deep_sort_pytorch@noreply.github.com&gt;; 
抄送: "2661180142"<2661180142@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZQPei/deep_sort_pytorch] 运行时 报ipython错误 (#89)




它提示你在用cpu跑了。
 如果没有GPU的话，你就把yolov3_deepsort.py里面的19-20行删掉就可以了。
