### ISSUE TITLE
Error using test.py

### ISSUE THREAD

**Issue by sandeshshrestha45** [ZQPei/deep_sort_pytorch#9]
Dear ZQPei, 
When i try to test my model using test.py, the following error occurs:
![Capture](https://user-images.githubusercontent.com/10694553/54069170-8ae82a80-4287-11e9-92d6-be24ecced3fa.PNG)

can u please tell me how can i fix this?

**Comment by ZQPei** [comment]
net = Net(reid=True, num_classes=1539)

**Comment by sandeshshrestha45** [comment]
Thanks. That worked. After running test.py and evaluate.py, i get the following output.
![Capture](https://user-images.githubusercontent.com/10694553/54081720-c47a6d80-433b-11e9-83c5-92d237d22637.PNG)

Can you please tell me what does it signify?

**Comment by ZQPei** [comment]
It means your top1 accuracy is 0.
There must be some error in your training schedule.
