### ISSUE TITLE
how can i change the detector to other algorithm

### ISSUE THREAD

**Issue by yustaub** [ZQPei/deep_sort_pytorch#90]
hello ZQPei, i want to change the detector yolov3 to other algotithm, can u tell me where I should change? thank u very much!!

**Comment by ZQPei** [comment]
This is simple.
See the code in `detector? Just add your detector beside the `YOLO` folder and remember to wrap your detector by defining a new class as I did in `detector/YOLOv3/detector.py`.
Hope this reply is not too late.

**Comment by yustaub** [comment]
@ZQPei thanks a lot!!!

**Comment by edgexspear** [comment]
> hello ZQPei, i want to change the detector yolov3 to other algotithm, can u tell me where I should change? thank u very much!!

do you successed？
