### ISSUE TITLE
python version NMS

### ISSUE THREAD

**Issue by yellowyi9527** [ZQPei/deep_sort_pytorch#92]
hello ,I have a warning ,How to deal with it?
detector/YOLOv3/nms/nms.py:16: UserWarning: You are using python version NMS, which is very very slow. Try compile c++ NMS using `cd ext & python build.py build_ext develop`

**Comment by yellowyi9527** [comment]
sudo pip3 install --upgrade torchvision

**Comment by yellowyi9527** [comment]
sudo pip3 install --upgrade torchvision

**Comment by ZQPei** [comment]
Hello, Dear yellowyi9527,
It seems that the NMS compiling was failed.
There are two solutions,
1. upgrade your pytorch version >= 1.1 and then you can also upgrade your torchvision >= 0.3
2. or you can upgrade your GCC to 5.x, and I think that will be OK.
You can email me if the warning stil exists.
