### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by quuhua911** [ZQPei/deep_sort_pytorch#95]
(pytorch) :~/pythonwork/deep_sort_pytorch$ python yolov3_deepsort.py demo1.mp4
/home/quh/pythonwork/deep_sort_pytorch/utils/parser.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
Traceback (most recent call last):
  File "yolov3_deepsort.py", line 112, in <module>
    with VideoTracker(cfg, args) as vdo_trk:
  File "yolov3_deepsort.py", line 23, in __init__
    cv2.namedWindow("test", cv2.WINDOW_NORMAL)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/highgui/src/window.cpp:610: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

**Comment by ZQPei** [comment]
Seems your opencv is compiled from source code and you have an opencv version 4.1.1.
This will be fixed by ignoring the display window with command `python yolov3_deepsort.py demo1.mp4 --ignore_display`.
The output video will be saved to `demo/demo.avi`.
Wish you luck.
